-- Generated file containing the data the Jukebox needs!

local rdata = {}


-- MUSIC/PUZZLES/IRELAND/ART_OF_ESCAPISM_-_GUARDIANS.MP3
rdata["MUSIC/PUZZLES/IRELAND/ART_OF_ESCAPISM_-_GUARDIANS.MP3"] = {}
rdata["MUSIC/PUZZLES/IRELAND/ART_OF_ESCAPISM_-_GUARDIANS.MP3"].Author = 'Art Of Escapism'
rdata["MUSIC/PUZZLES/IRELAND/ART_OF_ESCAPISM_-_GUARDIANS.MP3"].WebSite = 'https://soundcloud.com/theartofescapism'
rdata["MUSIC/PUZZLES/IRELAND/ART_OF_ESCAPISM_-_GUARDIANS.MP3"].Title = 'Guardians'

-- MUSIC/PUZZLES/EGYPT/HYPNOTIC-PUZZLE3.MP3
rdata["MUSIC/PUZZLES/EGYPT/HYPNOTIC-PUZZLE3.MP3"] = {}
rdata["MUSIC/PUZZLES/EGYPT/HYPNOTIC-PUZZLE3.MP3"].Author = 'Eric Matyas'
rdata["MUSIC/PUZZLES/EGYPT/HYPNOTIC-PUZZLE3.MP3"].WebSite = 'https://soundimage.org/'
rdata["MUSIC/PUZZLES/EGYPT/HYPNOTIC-PUZZLE3.MP3"].Title = 'Hypnotic'

-- MUSIC/PUZZLES/GERMANY/CHAMBER OF JEWELS.OGG
rdata["MUSIC/PUZZLES/GERMANY/CHAMBER OF JEWELS.OGG"] = {}
rdata["MUSIC/PUZZLES/GERMANY/CHAMBER OF JEWELS.OGG"].Author = 'Eric Matyas'
rdata["MUSIC/PUZZLES/GERMANY/CHAMBER OF JEWELS.OGG"].WebSite = 'https://soundimage.org/'
rdata["MUSIC/PUZZLES/GERMANY/CHAMBER OF JEWELS.OGG"].Title = 'Chamber of jewels'

-- MUSIC/BOSS/BOSS.OGG
rdata["MUSIC/BOSS/BOSS.OGG"] = {}
rdata["MUSIC/BOSS/BOSS.OGG"].Author = 'Kevin McLeod'
rdata["MUSIC/BOSS/BOSS.OGG"].WebSite = 'https://incompetec.com'
rdata["MUSIC/BOSS/BOSS.OGG"].Title = 'Agnus Dei X'

-- MUSIC/GENERAL/CALL TO ADVENTURE.MP3
rdata["MUSIC/GENERAL/CALL TO ADVENTURE.MP3"] = {}
rdata["MUSIC/GENERAL/CALL TO ADVENTURE.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/GENERAL/CALL TO ADVENTURE.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/GENERAL/CALL TO ADVENTURE.MP3"].Title = 'Call to Adventure'

-- MUSIC/PUZZLES/CHINA/ASIAN DRUMS.MP3
rdata["MUSIC/PUZZLES/CHINA/ASIAN DRUMS.MP3"] = {}
rdata["MUSIC/PUZZLES/CHINA/ASIAN DRUMS.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/CHINA/ASIAN DRUMS.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/CHINA/ASIAN DRUMS.MP3"].Title = 'Asian Drums'

-- MUSIC/PUZZLES/CHINA/EASTERN THOUGHT.MP3
rdata["MUSIC/PUZZLES/CHINA/EASTERN THOUGHT.MP3"] = {}
rdata["MUSIC/PUZZLES/CHINA/EASTERN THOUGHT.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/CHINA/EASTERN THOUGHT.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/CHINA/EASTERN THOUGHT.MP3"].Title = 'Eastern thought'

-- MUSIC/PUZZLES/EGYPT/RETURN OF THE MUMMY.MP3
rdata["MUSIC/PUZZLES/EGYPT/RETURN OF THE MUMMY.MP3"] = {}
rdata["MUSIC/PUZZLES/EGYPT/RETURN OF THE MUMMY.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/EGYPT/RETURN OF THE MUMMY.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/EGYPT/RETURN OF THE MUMMY.MP3"].Title = 'Return of the mummy'

-- MUSIC/PUZZLES/EGYPT/SILVER FLAME.MP3
rdata["MUSIC/PUZZLES/EGYPT/SILVER FLAME.MP3"] = {}
rdata["MUSIC/PUZZLES/EGYPT/SILVER FLAME.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/EGYPT/SILVER FLAME.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/EGYPT/SILVER FLAME.MP3"].Title = 'Silver Flame'

-- MUSIC/PUZZLES/GERMANY/TENEBROUS BROTHERS CARNIVAL - MERMAID.OGG
rdata["MUSIC/PUZZLES/GERMANY/TENEBROUS BROTHERS CARNIVAL - MERMAID.OGG"] = {}
rdata["MUSIC/PUZZLES/GERMANY/TENEBROUS BROTHERS CARNIVAL - MERMAID.OGG"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/GERMANY/TENEBROUS BROTHERS CARNIVAL - MERMAID.OGG"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/GERMANY/TENEBROUS BROTHERS CARNIVAL - MERMAID.OGG"].Title = 'Tenebrous Brothers Carnival'

-- MUSIC/PUZZLES/GREECE/ASCENDING THE VALUE.MP3
rdata["MUSIC/PUZZLES/GREECE/ASCENDING THE VALUE.MP3"] = {}
rdata["MUSIC/PUZZLES/GREECE/ASCENDING THE VALUE.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/GREECE/ASCENDING THE VALUE.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/GREECE/ASCENDING THE VALUE.MP3"].Title = 'Ascending the value'

-- MUSIC/PUZZLES/GREECE/ENCHANTED JOURNEY.MP3
rdata["MUSIC/PUZZLES/GREECE/ENCHANTED JOURNEY.MP3"] = {}
rdata["MUSIC/PUZZLES/GREECE/ENCHANTED JOURNEY.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/GREECE/ENCHANTED JOURNEY.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/GREECE/ENCHANTED JOURNEY.MP3"].Title = 'Enchanted Journey'

-- MUSIC/PUZZLES/IRELAND/CELTIC IMPULSE.MP3
rdata["MUSIC/PUZZLES/IRELAND/CELTIC IMPULSE.MP3"] = {}
rdata["MUSIC/PUZZLES/IRELAND/CELTIC IMPULSE.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/IRELAND/CELTIC IMPULSE.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/IRELAND/CELTIC IMPULSE.MP3"].Title = 'Celtic Impulse'

-- MUSIC/PUZZLES/ITALY/HERO DOWN.MP3
rdata["MUSIC/PUZZLES/ITALY/HERO DOWN.MP3"] = {}
rdata["MUSIC/PUZZLES/ITALY/HERO DOWN.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/ITALY/HERO DOWN.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/ITALY/HERO DOWN.MP3"].Title = 'Hero Down'

-- MUSIC/PUZZLES/ITALY/HEROIC AGE.MP3
rdata["MUSIC/PUZZLES/ITALY/HEROIC AGE.MP3"] = {}
rdata["MUSIC/PUZZLES/ITALY/HEROIC AGE.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/ITALY/HEROIC AGE.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/ITALY/HEROIC AGE.MP3"].Title = 'Heroic Age'

-- MUSIC/PUZZLES/NORWAY/SNOWDROP.MP3
rdata["MUSIC/PUZZLES/NORWAY/SNOWDROP.MP3"] = {}
rdata["MUSIC/PUZZLES/NORWAY/SNOWDROP.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/NORWAY/SNOWDROP.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/NORWAY/SNOWDROP.MP3"].Title = 'Snowdrop'

-- MUSIC/PUZZLES/NORWAY/THE NORTH.MP3
rdata["MUSIC/PUZZLES/NORWAY/THE NORTH.MP3"] = {}
rdata["MUSIC/PUZZLES/NORWAY/THE NORTH.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/NORWAY/THE NORTH.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/NORWAY/THE NORTH.MP3"].Title = 'The North'

-- MUSIC/PUZZLES/NORWAY/THE SNOW QUEEN.MP3
rdata["MUSIC/PUZZLES/NORWAY/THE SNOW QUEEN.MP3"] = {}
rdata["MUSIC/PUZZLES/NORWAY/THE SNOW QUEEN.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/NORWAY/THE SNOW QUEEN.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/NORWAY/THE SNOW QUEEN.MP3"].Title = 'The Snow Queen'

-- MUSIC/PUZZLES/YAHLEVANIA/DARK FOG.MP3
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK FOG.MP3"] = {}
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK FOG.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK FOG.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK FOG.MP3"].Title = 'Dark Fog'

-- MUSIC/PUZZLES/YAHLEVANIA/DARK WALK.MP3
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK WALK.MP3"] = {}
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK WALK.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK WALK.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/YAHLEVANIA/DARK WALK.MP3"].Title = 'Dark Walk'

-- MUSIC/PUZZLES/YAHLEVANIA/FINAL BATTLE OF THE DARK WIZARDS.MP3
rdata["MUSIC/PUZZLES/YAHLEVANIA/FINAL BATTLE OF THE DARK WIZARDS.MP3"] = {}
rdata["MUSIC/PUZZLES/YAHLEVANIA/FINAL BATTLE OF THE DARK WIZARDS.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/YAHLEVANIA/FINAL BATTLE OF THE DARK WIZARDS.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/YAHLEVANIA/FINAL BATTLE OF THE DARK WIZARDS.MP3"].Title = 'Final battle of the dark wizards'

-- MUSIC/PUZZLES/YAHLEVANIA/SUGAR PLUM DARK MIX.MP3
rdata["MUSIC/PUZZLES/YAHLEVANIA/SUGAR PLUM DARK MIX.MP3"] = {}
rdata["MUSIC/PUZZLES/YAHLEVANIA/SUGAR PLUM DARK MIX.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/YAHLEVANIA/SUGAR PLUM DARK MIX.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/YAHLEVANIA/SUGAR PLUM DARK MIX.MP3"].Title = 'Sugar Plum Fairy - Dark Mix'

-- MUSIC/ENDPUZZLE/MUSIC FOR FUNERAL HOME - PART 1.MP3
rdata["MUSIC/ENDPUZZLE/MUSIC FOR FUNERAL HOME - PART 1.MP3"] = {}
rdata["MUSIC/ENDPUZZLE/MUSIC FOR FUNERAL HOME - PART 1.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/ENDPUZZLE/MUSIC FOR FUNERAL HOME - PART 1.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/ENDPUZZLE/MUSIC FOR FUNERAL HOME - PART 1.MP3"].Title = 'Music for funeral home - part #1'

-- MUSIC/PUZZLES/EGYPT/EAST OF TUNESIA.WAV
rdata["MUSIC/PUZZLES/EGYPT/EAST OF TUNESIA.WAV"] = {}
rdata["MUSIC/PUZZLES/EGYPT/EAST OF TUNESIA.WAV"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/EGYPT/EAST OF TUNESIA.WAV"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/EGYPT/EAST OF TUNESIA.WAV"].Title = 'East of Tunesia'

-- MUSIC/PUZZLES/SPACE/FUTURE SETTING A.MP3
rdata["MUSIC/PUZZLES/SPACE/FUTURE SETTING A.MP3"] = {}
rdata["MUSIC/PUZZLES/SPACE/FUTURE SETTING A.MP3"].Author = 'Kevin McLeod'
rdata["MUSIC/PUZZLES/SPACE/FUTURE SETTING A.MP3"].WebSite = 'https://incompetec.com'
rdata["MUSIC/PUZZLES/SPACE/FUTURE SETTING A.MP3"].Title = 'Future Setting A'

-- MUSIC/PUZZLES/ATLANTIS/BEHIND THE MASK.MP3
rdata["MUSIC/PUZZLES/ATLANTIS/BEHIND THE MASK.MP3"] = {}
rdata["MUSIC/PUZZLES/ATLANTIS/BEHIND THE MASK.MP3"].Author = 'Nihilore'
rdata["MUSIC/PUZZLES/ATLANTIS/BEHIND THE MASK.MP3"].WebSite = 'http://www.nihilore.com/'
rdata["MUSIC/PUZZLES/ATLANTIS/BEHIND THE MASK.MP3"].Title = 'Behind the Mask'

-- MUSIC/PUZZLES/ATLANTIS/L'APPEL DU VIDE.MP3
rdata["MUSIC/PUZZLES/ATLANTIS/L'APPEL DU VIDE.MP3"] = {}
rdata["MUSIC/PUZZLES/ATLANTIS/L'APPEL DU VIDE.MP3"].Author = 'Nihilore'
rdata["MUSIC/PUZZLES/ATLANTIS/L'APPEL DU VIDE.MP3"].WebSite = 'http://www.nihilore.com/'
rdata["MUSIC/PUZZLES/ATLANTIS/L'APPEL DU VIDE.MP3"].Title = 'L\'appel du vide'

-- MUSIC/PUZZLES/GREECE/PLUSPLUS_-_01_-_GREEK_TRAGEDY.MP3
rdata["MUSIC/PUZZLES/GREECE/PLUSPLUS_-_01_-_GREEK_TRAGEDY.MP3"] = {}
rdata["MUSIC/PUZZLES/GREECE/PLUSPLUS_-_01_-_GREEK_TRAGEDY.MP3"].Author = 'Plusplus'
rdata["MUSIC/PUZZLES/GREECE/PLUSPLUS_-_01_-_GREEK_TRAGEDY.MP3"].Title = 'Greek Tragedy'

-- MUSIC/PUZZLES/GERMANY/TEARDROPS.OGG
rdata["MUSIC/PUZZLES/GERMANY/TEARDROPS.OGG"] = {}
rdata["MUSIC/PUZZLES/GERMANY/TEARDROPS.OGG"].Author = 'Wicky77'
rdata["MUSIC/PUZZLES/GERMANY/TEARDROPS.OGG"].Title = 'Teardrops'
